#!/usr/bin/env bash

# install-all-hsd v.1.3.0
# Installs handshake hsd (https://github.com/handshake-org/hsd)
# on Ubuntu (20.04 LTS preferred) or Debian

# Make sure you have at least 35GB storage free on your system!

HSDDATA="$HOME/.hsd"
LISTEN="true"
MAXINBOUND=800

####
if [ ! -f "/etc/debian_version" ]; then
  echo "Install script only for Ubuntu/Debian!"
  exit 1
fi

B="\e[1m"
G="\e[32m"
R="\e[31m"
E="\e[0m"
NL='
'
if [ -n "$1" ]; then
  if [ -d "$HSDDATA" ]; then
    echo "Data path $1 can't be set! Remove $HSDDATA first."
    exit 1
  else
    if mkdir -p ${1}; then
      HSDDATA="$1"
    else
      echo "Data path $1 can't be set!"
      exit 1
    fi
  fi
fi

function check_hsd {
  HSDRUNNING=$(pgrep -cx hsd)
  if [ $HSDRUNNING -eq 1 ]; then
    HSDVERSION="$(hsd-cli info|jq -r .version)"
    HSDUPDATE=1
  else
    HSDUPDATE=0
    if [ -d "${HOME}/hsd" ]; then
      HSDUPDATE=1
    fi
  fi
}

function initialsetup {
  sudo timedatectl set-timezone UTC

  sudo apt update
  sudo apt upgrade -y

  sudo apt -y install git nodejs npm build-essential curl jq libunbound-dev gpg socat dnsutils

  sudo npm install -g n
  sudo n lts
  sudo npm install -g node-gyp

  NODE="$(which node)"
  if [ ! "$NODE" ]; then
    echo -e "${R}Node not (properly) installed!${E}"
    exit 1
  fi
}

function installkeys {
  # Install keys from devs (https://github.com/handshake-org/hsd/blob/master/SECURITY.md)
  gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys "B4B1F62DBAC084E333F3A04A8962AB9DE6666BBD"
  gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys "E61773CD6E01040E2F1BD78CE7E2984B6289C93A"
  gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys "D2B2828BD29374D5E9BA3E52CCE677B05CC0FE23"
}

function verifykeys {
  git verify-tag latest
  RC=$?
  if [ $RC -ne 0 ]; then
    echo -e "${R}Installed code can't be verified!${E}"
    echo "See https://github.com/handshake-org/hsd/blob/master/SECURITY.md"
    exit 1
  fi
}

function install_hsd {
  cd ${HOME}

  git clone --depth 1 --branch latest https://github.com/handshake-org/hsd.git

  cd hsd

  verifykeys

  npm install --production
  sudo npm install -g hs-client
}

function update_hsd {
  cd ${HOME}/hsd

  git pull

  verifykeys
  echo
  echo "If a new version is installed, activate it by restarting hsd:"
  echo -e "${G}sudo systemctl restart hsd${E}"
}

function service_hsd {
  HSDSVCFILE="/lib/systemd/system/hsd.service"

  HSDSVCTXT=$(echo -e "[Unit]
Description=hsd
After=network.target

[Service]
Type=simple
Restart=always
RestartSec=1
User=root
Environment=HSD_PREFIX=$HSDDATA
ExecStart=${NODE} ${HOME}/hsd/bin/hsd --no-wallet

[Install]
WantedBy=multi-user.target
")

  echo "$HSDSVCTXT" | sudo tee $HSDSVCFILE > /dev/null

  sudo systemctl daemon-reload
  sudo systemctl enable hsd.service
}

function config_hsd {
  MYIP=$(dig @resolver4.opendns.com myip.opendns.com +short)

  HSDCFGFILE="${HSDDATA}/hsd.conf"

  HSDCFGTXT=$(echo -e "log-level: info
listen: $1
bip37: true
public-host: $MYIP
max-inbound: $MAXINBOUND
")

  mkdir -p $HSDDATA
  echo "$HSDCFGTXT" >$HSDCFGFILE
}

function start_hsd {
  sudo systemctl start hsd
  sleep 5s
  if [ "$(systemctl is-active hsd)" = "active" ]; then
    HSDVERSION="$(hsd-cli info|jq -r .version)"
    echo -e "${NL}${G}###${E}"
    echo -e "${NL}${G}hsd $HSDVERSION successfully started as service!${E}"
  else
    echo -e "${NL}${R}hsd service not started!${E}"
    exit 1
  fi
}

function show_config {
  echo -e "
${B}Current hsd config file${E} ($HSDCFGFILE):

###
$(cat $HSDCFGFILE)
###

Syncing the chain may take few hours (depending on hardware/env.)

Currently hsd is set as non-listening node.

Some Commands:
hsd service status:   ${B}systemctl status hsd${E}
hsd service restart:  ${B}sudo systemctl restart hsd${E}
"

if [ "$LISTEN" = "true" ]; then
  echo -e "${G}After the chain is 100% synced${E} please ${G}restart hsd${E} or even reboot
your system to change hsd to a listening public full node with $MAXINBOUND
allowed inbound connections. This is great support for Handshake!"
fi
}

function show_block {
  echo -e "${NL}hsd is running as a service, you can stop this script at any time (Ctrl-C)${NL}"
  while true; do
    HSDINFO="$(hsd-cli info)"
    BLOCK="$(echo "$HSDINFO"|jq .chain.height)"
    PROGESS="$(echo "$HSDINFO"|jq .chain.progress)"
    PROGRESS=$(awk "BEGIN {printf \"%.1f\n\", ${PROGESS}*100}")
    echo -n -e "\r${G}hsd $HSDVERSION is syncing${E} - current block height: ${G}$BLOCK (${PROGRESS%\.*}%)${E}"
    for i in {1..10}; do
      sleep 1s
      printf '.'
    done
  done
}

# Main

check_hsd
if [ $HSDUPDATE -eq 0 ]; then
  initialsetup
  installkeys
  install_hsd
  service_hsd
  config_hsd false
  start_hsd
  show_config
  config_hsd $LISTEN
  show_block
else
  update_hsd
  if [ $HSDRUNNING -eq 1 ]; then
    show_block
  else
    echo
    echo "hsd is installed but not running."
    echo -e "To start hsd: ${G}sudo systemctl start hsd${E}"
  fi
fi

exit
